CREATE TABLE PRODUCT_TYPE (
    ID BIGINT IDENTITY PRIMARY KEY,
    PRODUCT VARCHAR2 NOT NULL
);

CREATE TABLE SALE (
    PRODUCT_TYPE_ID BIGINT NOT NULL,
    ORIGINAL_PRICE NUMERIC,
    PRICE NUMERIC,
    OCCURRENCES INTEGER,
    FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE(ID)
);

CREATE TABLE ADJUSTMENTS (
    ID BIGINT IDENTITY PRIMARY KEY,
    PRODUCT_TYPE_ID BIGINT NOT NULL,
    ACTION VARCHAR2(8),
    OPERAND NUMERIC,
    FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE(ID)
);